version: '3.8'

networks:
  mongo-network:
    driver: bridge

services:
  mongo1:
    image: mongo:latest
    container_name: mongodb1
    hostname: mongo1
    networks:
      - mongo-network
    volumes:
      - mongo1-data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    healthcheck:
      test: |
        mongosh --host mongo1:27017 --eval         'try { db.adminCommand("ping").ok } catch (e) { print(e); quit(1); }' --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  mongo2:
    image: mongo:latest
    container_name: mongodb2
    hostname: mongo2
    networks:
      - mongo-network
    volumes:
      - mongo2-data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    healthcheck:
      test: |
        mongosh --host mongo2:27017 --eval         'try { db.adminCommand("ping").ok } catch (e) { print(e); quit(1); }' --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  mongo3:
    image: mongo:latest
    container_name: mongodb3
    hostname: mongo3
    networks:
      - mongo-network
    volumes:
      - mongo3-data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    healthcheck:
      test: |
        mongosh --host mongo3:27017 --eval         'try { db.adminCommand("ping").ok } catch (e) { print(e); quit(1); }' --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    networks:
      - mongo-network
    volumes:
      - ./init-replica-set.sh:/scripts/init-replica-set.sh # Assuming init-replica-set.sh is in the same dir as docker-compose.yml
    command: ["/bin/bash", "/scripts/init-replica-set.sh"]
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
